x-common: &common
  build:
    context: .
    dockerfile: Dockerfile
  init: true # Auto-reap zombie processes and forward process signals
  environment:
    RUST_BACKTRACE: "full"

services:
  node1:
    <<: *common
    command: ["./snapchain", "--config-path", "/app/data/snapchain.toml"]
    ports:
      - "50051:50051/udp"
      - "3381:3381/tcp"
      - "3383:3383/tcp"
      - "3483:3483"
    networks:
      snapchain-subnet:
        ipv4_address: 172.100.0.11
    volumes:
      - ./nodes/1:/app/data
  node2:
    <<: *common
    command: ["./snapchain", "--config-path", "/app/data/snapchain.toml"]
    ports:
      - "50052:50052/udp"
      - "3384:3384/tcp"
      - "3484:3484"
    networks:
      snapchain-subnet:
        ipv4_address: 172.100.0.12
    volumes:
      - ./nodes/2:/app/data
  node3:
    <<: *common
    command: ["./snapchain", "--config-path", "/app/data/snapchain.toml"]
    ports:
      - "50053:50053/udp"
      - "3385:3385/tcp"
      - "3485:3485"
    networks:
      snapchain-subnet:
        ipv4_address: 172.100.0.13
    volumes:
      - ./nodes/3:/app/data
  node4:
    <<: *common
    command: ["./snapchain", "--config-path", "/app/data/snapchain.toml"]
    ports:
      - "50054:50054/udp"
      - "3386:3386/tcp"
      - "3486:3486"
    networks:
      snapchain-subnet:
        ipv4_address: 172.100.0.14
    volumes:
      - ./nodes/4:/app/data

networks:
  snapchain-subnet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.100.0.0/24
