apiVersion: 1

datasources:
  - name: Graphite
    type: graphite
    access: proxy
    url: http://graphite
    isDefault: true
    jsonData:
      graphiteVersion: "1.1"
      tlsAuth: false
      tlsAuthWithCACert: false
