stats_calculation_interval = "2s"
num_iterations = 120

[submit_message]
rpc_addrs = [
    "http://127.0.0.1:3383",
]
interval = "1000us"
auth = "user:test"

[follow_blocks]
rpc_addr = "http://127.0.0.11:3383"
enable = false 